package oa.spring.dao.batis;

import java.util.List;
import java.util.Map;


public interface ProduceMapper {
	public Map<String,Object> getCrafts(String craftsId);
	public Map<String,Object> getType(String typeId);
	public Map<String,Object> getDrawingType(String drawingTypeId);
	public Map<String,Object> selectProductByProId(String proId);
	public Map<String,Object> getDrawingTypeByDtId(String dt_id);
	public Map<String,Object> getProduct(String proId);
	public Map<String,Object> getProductInfo(String proId);
	public Map<String,Object> getProcessByIds(String id);
	public Map<String,Object> getNotifyById(String notifyId);
	public Map<String,Object> getPlan(String planId);
	public Map<String,Object> getPlanCode(String planId);
	public Map<String,Object> getProcessIndex(Map map);
	public List getMachineType();
	public List<Map<String,Object>> getWareHouse();
	public List<Map<String,Object>> getProcessById(String craftsId);
	public List<Map<String,Object>> getBOMList(String crafts_id);
	public List<Map<String,Object>> getPlanProNumberList(String planId);
	public List<Map<String,Object>> getBOMInfoList(Map<String,Object> map);
	public List<Map<String,Object>> getBOMDetial(Map<String,String> map);
	public List<Map<String,Object>> getExamInfoList(String planId);
	public List<Map<String,Object>> getExamProDetial(Map<String,String> map);
	public List getNotifyProById(String notifyId);
	public List<Map<String,Object>> getPlanPro(String planId);
	public List getProcessPro(String process_id);
	public void addBOM(Map<String,Object> map);
	public void addExam(Map<String,Object> map);
	public void addCrafts(Map<String,Object> map);
	public void addProcess(Map<String,Object> map);
	public void updateProcess(Map<String,Object> map);
	public void updatePlan(Map<String,Object> map);
	public void updateNotify(Map<String,Object> map);
	public void addNotify(Map<String,Object> map);
	public void addNotifyPro(List<Map<String,Object>> list);
	public void addPlan(Map<String,Object> map);
	public void addBOMPros(List list);
	public void addExamPros(List list);
	public void addDBLog(List<Map<String,Object>> list);
	public void addDBLog1(List<Map<String,Object>> list);
	public void updateExamDetial(Map map);
	public void updateExam(Map map);
	public void addPlanPro(List list);
	public void addProcessConsume(List list);
	public void deleteProcessConsume(String processId);
	public void deleteNotify(String notifyId);
	public void deleteNoPro(String notifyId);
	public void  deleteProcess(String processId);
	public void addType(Map<String,Object> map);
	public void addDrawingType(Map<String,Object> map);
	public void updateCrafts(Map map);
	public void updateType(Map map);
	public void updateDrawingType(Map map);
	public void updateDrawing(Map map);
	public void deleteCrafts(String craftsId);
	public void deleteType(String typeId);
	public void deleteDrawingType(String drawingTypeId);
	public Map<String, Object> getDrawing(String drawingId);
	public void deleteDrawing(String drawingId);
	public void deletePlan(String planId);
	public void deletePlanPro(String planId);
	public void addDrawing(Map map);
	public void updateBOMInfo(Map map);
	public void deleteBOMPro(String bom_id);
	public void deleteDBLog(Map<String,String> map);
	public void changeExamWay(Map<String,String> map);
}
