<%@ taglib prefix="s" uri="/struts-tags" %> 
<html>
	<head>
		<title>Hello Page</title>
	</head>
	<body>
		The message generated by my first action is:
		<s:property value="message" />		
	</body>
</html>
